name: Deploy to Kubernetes

on:
  workflow_call:
    inputs:
      deployment-file:
        required: true
        type: string
      service-file:
        required: true
        type: string
    secrets:
      required:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.21.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ${{ inputs.deployment-file }}
          kubectl apply -f ${{ inputs.service-file }}
